[versions]
android_gradle = '8.7.0'
gradle_publish = '1.2.2'
plugin_version = '1.3.5'
annotations    = '23.0.0'
httpcore       = '4.4.16'
httpclient     = '4.5.14'
httpmime       = '4.5.14'
junit          = '5.8.2'
gson           = '2.10.1'

[plugins]
maven_publish  = { id = "maven-publish" }
gradle_plugin  = { id = "org.gradle.java-gradle-plugin" }
gradle_publish = { id = "com.gradle.plugin-publish", version.ref = "gradle_publish" }

# The plugin can be defined in other projects alike this:
# agconnect_publishing = { id = "io.syslogic.agconnect.publishing", version.ref = "plugin_version" }

[libraries]
android_gradle = { module = "com.android.tools.build:gradle-api", version.ref = "android_gradle" }
annotations    = { module = "org.jetbrains:annotations", version.ref = "annotations" }
httpcore       = { module = "org.apache.httpcomponents:httpcore", version.ref = "httpcore" }
httpclient     = { module = "org.apache.httpcomponents:httpclient", version.ref = "httpclient" }
httpmime       = { module = "org.apache.httpcomponents:httpmime", version.ref = "httpmime" }
junit          = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
gson           = { module = "com.google.code.gson:gson", version.ref = "gson" }

[bundles]
http_components = ["httpcore", "httpclient", "httpmime", "gson"]
